In [2]:
import seaborn as sb
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

In [4]:
import pandas as pd

In [35]:
from sklearn.neighbors import NearestNeighbors

In [5]:
link='/Users/afatade/Downloads/anime_cleaned.csv'
data=pd.read_csv(link)

In [6]:
data.head()

anime_id                title              title_english title_japanese  \
0     11013        Inu x Boku SS  Inu X Boku Secret Service         妖狐×僕SS   
1      2104     Seto no Hanayome      My Bride is a Mermaid          瀬戸の花嫁   
2      5262   Shugo Chara!! Doki         Shugo Chara!! Doki    しゅごキャラ！！どきっ   
3       721        Princess Tutu              Princess Tutu      プリンセスチュチュ   
4     12365  Bakuman. 3rd Season                   Bakuman.          バクマン。   

                                  title_synonyms  \
0                                Youko x Boku SS   
1                           The Inland Sea Bride   
2  Shugo Chara Ninenme, Shugo Chara! Second Year   
3                                            NaN   
4                               Bakuman Season 3   

                                           image_url type    source  episodes  \
0  https://myanimelist.cdn-dena.com/images/anime/...   TV     Manga        12   
1  https://myanimelist.cdn-dena.com/images/anime/...   TV     Manga        26   
2  https://myanimelist.cdn-dena.com/images/anime/...   TV     Manga        51   
3  https://myanimelist.cdn-dena.com/images/anime/...   TV  Original        38   
4  https://myanimelist.cdn-dena.com/images/anime/...   TV     Manga        25   

            status       ...                  broadcast  \
0  Finished Airing       ...         Fridays at Unknown   
1  Finished Airing       ...                    Unknown   
2  Finished Airing       ...                    Unknown   
3  Finished Airing       ...         Fridays at Unknown   
4  Finished Airing       ...                    Unknown   

                                             related  \
0  {'Adaptation': [{'mal_id': 17207, 'type': 'man...   
1  {'Adaptation': [{'mal_id': 759, 'type': 'manga...   
2  {'Adaptation': [{'mal_id': 101, 'type': 'manga...   
3  {'Adaptation': [{'mal_id': 1581, 'type': 'mang...   
4  {'Adaptation': [{'mal_id': 9711, 'type': 'mang...   

                                            producer          licensor  \
0  Aniplex, Square Enix, Mainichi Broadcasting Sy...  Sentai Filmworks   
1                  TV Tokyo, AIC, Square Enix, Sotsu        Funimation   
2                                    TV Tokyo, Sotsu               NaN   
3                 Memory-Tech, GANSIS, Marvelous AQL         ADV Films   
4                                      NHK, Shueisha               NaN   

             studio                                     genre  \
0  David Production    Comedy, Supernatural, Romance, Shounen   
1             Gonzo  Comedy, Parody, Romance, School, Shounen   
2         Satelight             Comedy, Magic, School, Shoujo   
3    Hal Film Maker    Comedy, Drama, Magic, Romance, Fantasy   
4         J.C.Staff           Comedy, Drama, Romance, Shounen   

                                       opening_theme  \
0                              ['"Nirvana" by MUCC']   
1                 ['"Romantic summer" by SUN&LUNAR']   
2  ['#1: "Minna no Tamago (みんなのたまご)" by Shugo Cha...   
3             ['"Morning Grace" by Ritsuko Okazaki']   
4  ['#1: "Moshimo no Hanashi (もしもの話)" by nano.RIP...   

                                        ending_theme  duration_min  \
0  ['#1: "Nirvana" by MUCC (eps 1, 11-12)', '#2: ...          24.0   
1  ['#1: "Ashita e no Hikari (明日への光)" by Asuka Hi...          24.0   
2  ['#1: "Rottara Rottara (ロッタラ ロッタラ)" by Buono! ...          24.0   
3  ['"Watashi No Ai Wa Chiisaikeredo" by Ritsuko ...          16.0   
4  ['#1: "Pride on Everyday" by Sphere (eps 1-13)...          24.0   

   aired_from_year  
0           2012.0  
1           2007.0  
2           2008.0  
3           2002.0  
4           2012.0  

[5 rows x 33 columns]

In [15]:
len(data)

6668

In [7]:
#We have a lot of data. Lets see what we can do about our type and genre columns.

In [14]:
#Now we want to make use of our genres and type columns. These are very important when considering the type of anime one 
#wishes to make use of. We can call the pd.get_dummies function to generate a one hot encoded dataset.

#For the genres column, we will call str.get_dummies() and set our seperator to ','. This was we can
#do the dame for the genres column.

In [16]:
data.isnull().sum()

anime_id              0
title                 0
title_english      3230
title_japanese        5
title_synonyms     2187
image_url             2
type                  0
source                0
episodes              0
status                0
airing                0
aired_string          0
aired                 0
duration              0
rating                0
score                 0
scored_by             0
rank                356
popularity            0
members               0
favorites             0
background         5855
premiered          3702
broadcast          3688
related               0
producer           2266
licensor           3881
studio                0
genre                 4
opening_theme         0
ending_theme          0
duration_min          0
aired_from_year       0
dtype: int64

In [17]:
#We see we're missing some entrie for certain variables, but thats okay. We wont be using these variables.
#Lets isolate type, source,episodes and genre. These are really important features for recommending
#similar anime. Lets keep it simple.

In [21]:
#We need to generate one hot encoded columns for type, source and tv. Lets go

type_encoded=pd.get_dummies(data['type'])

In [22]:
type_encoded.head()

Movie  Music  ONA  OVA  Special  TV
0      0      0    0    0        0   1
1      0      0    0    0        0   1
2      0      0    0    0        0   1
3      0      0    0    0        0   1
4      0      0    0    0        0   1

In [23]:
source_encoded=pd.get_dummies(data['source'])

In [24]:
source_encoded.head()

4-koma manga  Book  Card game  Digital manga  Game  Light novel  Manga  \
0             0     0          0              0     0            0      1   
1             0     0          0              0     0            0      1   
2             0     0          0              0     0            0      1   
3             0     0          0              0     0            0      0   
4             0     0          0              0     0            0      1   

   Music  Novel  Original  Other  Picture book  Radio  Visual novel  Web manga  
0      0      0         0      0             0      0             0          0  
1      0      0         0      0             0      0             0          0  
2      0      0         0      0             0      0             0          0  
3      0      0         1      0             0      0             0          0  
4      0      0         0      0             0      0             0          0

In [25]:
#The type column has a lot of factors that the typical anime fanatic doesn't look into.
#Typically we only look at manga for the most part. However, we will consider using these features later.

#There are a lot of values per row in the genres column. It would be logical to make use of a 
#one hot encoding mechanism that makes use of a seperator.

genre_encoded=data['genre'].str.get_dummies(sep=',')

In [27]:
genre_encoded.head().values

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0

In [28]:
#We see our values have been encoded successfully.

#Lets create a new data frame with our episodes list and our encoded values

features=pd.concat([genre_encoded, type_encoded,data['episodes']],axis=1)

In [29]:
features.head()

Adventure   Cars   Comedy   Dementia   Demons   Drama   Ecchi   Fantasy  \
0           0      0        0          0        0       0       0         0   
1           0      0        0          0        0       0       0         0   
2           0      0        0          0        0       0       0         0   
3           0      0        0          0        0       1       0         1   
4           0      0        0          0        0       1       0         0   

    Game   Harem    ...     Supernatural  Thriller  Yaoi  Movie  Music  ONA  \
0      0       0    ...                0         0     0      0      0    0   
1      0       0    ...                0         0     0      0      0    0   
2      0       0    ...                0         0     0      0      0    0   
3      0       0    ...                0         0     0      0      0    0   
4      0       0    ...                0         0     0      0      0    0   

   OVA  Special  TV  episodes  
0    0        0   1        12  
1    0        0   1        26  
2    0        0   1        51  
3    0        0   1        38  
4    0        0   1        25  

[5 rows x 88 columns]

In [30]:
#Now we know our data has features with differing magnitudes. It would be logical to scale this data.

features_scaled=MinMaxScaler().fit_transform(features)

In [32]:
features_scaled[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 1.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 1.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       1.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [36]:
#This is just one feature element that we are going to chuck into our KNN algorithm

collaborative_filter=NearestNeighbors().fit(features_scaled)

In [38]:
collaborative_filter.kneighbors([features_scaled[0]])

(array([[0., 1., 1., 1., 1.]]), array([[   0, 4893, 2668, 3943, 4664]]))

In [50]:
data['title'].iloc[[0, 4893, 2668, 3943, 4664],].values

array(['Inu x Boku SS', 'Kami nomi zo Shiru Sekai',
       'Kami nomi zo Shiru Sekai II',
       'Saikin, Imouto no Yousu ga Chotto Okashiinda ga.',
       'Gugure! Kokkuri-san'], dtype=object)

In [ ]:
#Okay. We see that this filtering mechanism works very well!
#Lets see if we can generate a function such that when a user enters a name, a new anime is recommended

In [75]:
#Lets create some functions so this data looks neater overall.

def preprocess_data():
    link='/Users/afatade/Downloads/anime_cleaned.csv'
    data=pd.read_csv(link)
    type_encoded=pd.get_dummies(data['type'])
    source_encoded=pd.get_dummies(data['source'])
    genre_encoded=data['genre'].str.get_dummies(sep=',')
    features=pd.concat([genre_encoded, type_encoded,data['episodes']],axis=1)
    features_scaled=MinMaxScaler().fit_transform(features)
    return features_scaled

In [110]:
#This function will return the name of the anime in the dataset even if it is entered partially

def get_partial_names(title):
    names=list(data.title.values)
    for name in names:
        if title in name:
            return [name, names.index(name)]
        
#This function will return features for recommendation
def get_features(title):
    values=get_partial_names(title)
    return values[1]

def get_vector(title):
    index=get_features(title)
    data=preprocess_data()
    return data[index]

def collaborative_filter():
    data=preprocess_data()
    filtering=NearestNeighbors().fit(data)
    return filtering
    

def get_recommendations(title):
    vectorized_input=get_vector(title)
    filter_model=collaborative_filter()
    indices=filter_model.kneighbors([vectorized_input])[1]
    recommendations=data['title'].iloc[indices[0],].values
    return recommendations

In [114]:
get_recommendations("One Piece")

array(['One Piece', 'Digimon Frontier',
       'One Piece: Episode of Merry - Mou Hitori no Nakama no Monogatari',
       'One Piece: Episode of East Blue - Luffy to 4-nin no Nakama no Daibouken',
       'One Piece: Episode of Sabo - 3 Kyoudai no Kizuna Kiseki no Saikai to Uketsugareru Ishi'],
      dtype=object)

In [105]:
#Lovely! We'll work on the user interface later.